<?php
// 由 make:actor 生成 — 业务 Actor 骨架（kind=monster → extends BaseMonster，钩子集：onPatrol/onChase/onAttack/onDead/onDeath）。
// Generated by make:actor — business actor skeleton (kind=monster → extends BaseMonster; hooks: onPatrol/onChase/onAttack/onDead/onDeath).
declare(strict_types=1);

namespace {ns};

use Nythros\Framework\BaseMonster;

final class {class} extends {base}
{
    public function __construct(string $id, int $maxHp = 100)
    {
        parent::__construct($id, $maxHp);
    }

    protected function onPatrol(): void
    {
        // TODO: 巡逻钩子（感知视野内最近玩家 → CHASE + setTarget）
        // TODO: patrol hook (sense nearest player in vision → CHASE + setTarget)
    }

    protected function onChase(): void
    {
        // TODO: 追击钩子（目标丢失 → PATROL；进入攻击范围 → ATTACK）
        // TODO: chase hook (target lost → PATROL; within attack range → ATTACK)
    }

    protected function onAttack(): void
    {
        // TODO: 攻击钩子（冷却判定 → 攻击结算）
        // TODO: attack hook (cooldown check → attack settlement)
    }

    protected function onDead(): void
    {
        // TODO: 死亡帧钩子（DEAD 状态下每帧调用）
        // TODO: death frame hook (invoked every frame while in DEAD)
    }

    protected function onDeath(): void
    {
        // TODO: 死亡结算钩子（掉落 roll → spawnDrops → 自清理）
        // TODO: death settlement hook (drop roll → spawnDrops → self cleanup)
    }
}
