<?php
// 由 make:actor 生成 — 业务 Actor 骨架（kind=npc → extends BaseNPC，钩子集：onIdle/onInteract）。
// Generated by make:actor — business actor skeleton (kind=npc → extends BaseNPC; hooks: onIdle/onInteract).
declare(strict_types=1);

namespace {ns};

use Nythros\Framework\BaseNPC;
use Nythros\Framework\BasePlayer;

final class {class} extends {base}
{
    public function __construct(string $id)
    {
        parent::__construct($id);
    }

    protected function onIdle(): void
    {
        // TODO: 空闲钩子（定时刷新 / 被动行为）
        // TODO: idle hook (periodic refresh / passive behavior)
    }

    public function onInteract(BasePlayer $player): void
    {
        // TODO: 交互入口（对话 / 商店）
        // TODO: interaction entry (dialogue / shop)
    }
}
