<?php
// 由 make:actor 生成 — 业务 Actor 骨架（kind=player → extends BasePlayer，钩子集：onTick/onDamaged/onDeath）。
// Generated by make:actor — business actor skeleton (kind=player → extends BasePlayer; hooks: onTick/onDamaged/onDeath).
declare(strict_types=1);

namespace {ns};

use Nythros\Framework\BasePlayer;

final class {class} extends {base}
{
    public function __construct()
    {
        parent::__construct();
    }

    protected function onTick(): void
    {
        // TODO: 每帧钩子（冷却递减 / 状态刷新）
        // TODO: per-frame hook (cooldown decay / state refresh)
    }

    protected function onDamaged(int $amount): void
    {
        // TODO: 受伤钩子（属性同步 / 受击表现）
        // TODO: damage hook (stats sync / hit feedback)
    }

    protected function onDeath(): void
    {
        // TODO: 死亡结算钩子（标记待复活 / 回出生点）
        // TODO: death settlement hook (mark for revival / respawn point)
    }
}
