<?php

declare(strict_types=1);

namespace Nythros\Framework\Make;

use InvalidArgumentException;

/**
 * make:map — 生成地图配置条目并追加到地图配置（config/maps.php）。
 * make:map — generates a map config entry and appends it to the map config (config/maps.php).
 */
final class MakeMap extends MakeCommand
{
    /**
     * 执行 make:map：校验参数 → 渲染地图条目 → 追加到 --out 指定的配置。
     * Runs make:map: validates arguments → renders the map entry → appends it to the config at --out.
     *
     * @param list<string> $args 命令行参数（地图名 + --out + 可选宽高） Command-line arguments (map name + --out + optional width/height).
     *
     * @return string 生成/更新的配置文件路径 The generated or updated config file path.
     */
    public function run(array $args): string
    {
        $parsed = $this->parseArgs($args);
        $name = $parsed['name'];
        if ($name === null) {
            throw new InvalidArgumentException('缺少地图名参数（用法: make:map <地图名> --out=<maps.php> [--width=100 --height=100]）');
        }
        $this->assertIdentifier($name, '地图名');

        $out = $parsed['options']['out'] ?? null;
        if ($out === null || $out === '') {
            throw new InvalidArgumentException('缺少 --out 选项（地图配置文件路径）');
        }

        $id = $this->kebabize($name);
        $width = (int) $this->numericOption($parsed['options'], 'width', 100);
        $height = (int) $this->numericOption($parsed['options'], 'height', 100);
        $entry = [
            'id' => $id,
            'name' => $name,
            'width' => $width,
            'height' => $height,
        ];

        $entries = $this->loadConfig($out);
        if (isset($entries[$id])) {
            throw new InvalidArgumentException(sprintf('地图已存在: %s（id=%s）', $name, $id));
        }
        $entries[$id] = $entry;

        $this->writeFile($out, $this->renderMapConfig($entries));

        return $out;
    }

    /**
     * 渲染完整地图配置（头部 + 逐条目模板）。
     * Renders the full map config (header + one template per entry).
     *
     * @param array<string, array<string, mixed>> $entries 地图配置集合 The map config collection.
     */
    private function renderMapConfig(array $entries): string
    {
        $entryTemplate = $this->readTemplate('map.php.tpl');
        $items = '';
        foreach ($entries as $id => $entry) {
            $items .= str_replace(
                ['{id}', '{name}', '{width}', '{height}'],
                [
                    $id,
                    $this->phpString((string) $entry['name']),
                    (string) (int) $entry['width'],
                    (string) (int) $entry['height'],
                ],
                $entryTemplate,
            );
        }

        return "<?php\n"
            . "\n"
            . "declare(strict_types=1);\n"
            . "\n"
            . "// 由 make:map 生成 — 地图配置（部署/装配层消费）。\n"
            . "// Generated by make:map — map config (consumed by the deployment/assembly layer).\n"
            . "\n"
            . "return [\n"
            . $items
            . "];\n";
    }

    /**
     * 名称转 kebab-case id（如 Forest → forest）。
     * Converts a name to a kebab-case id (e.g. Forest → forest).
     */
    private function kebabize(string $name): string
    {
        return strtolower((string) preg_replace('/(?<!^)[A-Z]/', '-$0', $name));
    }

    /**
     * 值转 PHP 字符串内容（转义单引号，不含外层引号——模板已提供引号）。
     * Converts a value to PHP string contents (single quotes escaped, without the outer quotes — the template supplies them).
     */
    private function phpString(string $value): string
    {
        return str_replace("'", "\\'", $value);
    }
}
