<?php

declare(strict_types=1);

namespace Nythros\Framework\Make;

use InvalidArgumentException;

/**
 * make:skill — 生成技能定义条目并追加到技能配置（config/skills.php）。
 * make:skill — generates a skill definition entry and appends it to the skill config (config/skills.php).
 */
final class MakeSkill extends MakeCommand
{
    /**
     * 执行 make:skill：校验参数 → 渲染技能条目 → 追加到 --out 指定的配置。
     * Runs make:skill: validates arguments → renders the skill entry → appends it to the config at --out.
     *
     * @param list<string> $args 命令行参数（技能名 + --out + 可选数值项） Command-line arguments (skill name + --out + optional numeric items).
     *
     * @return string 生成/更新的配置文件路径 The generated or updated config file path.
     */
    public function run(array $args): string
    {
        $parsed = $this->parseArgs($args);
        $name = $parsed['name'];
        if ($name === null) {
            throw new InvalidArgumentException('缺少技能名参数（用法: make:skill <技能名> --out=<skills.php>）');
        }
        $this->assertIdentifier($name, '技能名');

        $out = $parsed['options']['out'] ?? null;
        if ($out === null || $out === '') {
            throw new InvalidArgumentException('缺少 --out 选项（技能配置文件路径）');
        }

        $id = $this->kebabize($name);
        $entry = [
            'id' => $id,
            'name' => $name,
            'damageMultiplier' => $this->numericOption($parsed['options'], 'damage-multiplier', 1.0),
            'cooldownSeconds' => $this->numericOption($parsed['options'], 'cooldown-seconds', 3.0),
            'range' => (int) $this->numericOption($parsed['options'], 'range', 5),
        ];

        $entries = $this->loadConfig($out);
        if (isset($entries[$id])) {
            throw new InvalidArgumentException(sprintf('技能已存在: %s（id=%s）', $name, $id));
        }
        $entries[$id] = $entry;

        $this->writeFile($out, $this->renderSkillConfig($entries));

        return $out;
    }

    /**
     * 渲染完整技能配置（头部 + 逐条目模板）。
     * Renders the full skill config (header + one template per entry).
     *
     * @param array<string, array<string, mixed>> $entries 技能定义集合 The skill definition collection.
     */
    private function renderSkillConfig(array $entries): string
    {
        $entryTemplate = $this->readTemplate('skill.php.tpl');
        $items = '';
        foreach ($entries as $id => $entry) {
            $items .= str_replace(
                ['{id}', '{name}', '{damageMultiplier}', '{cooldownSeconds}', '{range}'],
                [
                    $id,
                    $this->phpString((string) $entry['name']),
                    $this->phpNumber($entry['damageMultiplier']),
                    $this->phpNumber($entry['cooldownSeconds']),
                    $this->phpNumber($entry['range']),
                ],
                $entryTemplate,
            );
        }

        return "<?php\n"
            . "\n"
            . "declare(strict_types=1);\n"
            . "\n"
            . "// 由 make:skill 生成 — 技能定义配置（SkillRepository 消费）。\n"
            . "// Generated by make:skill — skill definition config (consumed by SkillRepository).\n"
            . "\n"
            . "return [\n"
            . $items
            . "];\n";
    }

    /**
     * 名称转 kebab-case id（如 Fireball → fireball）。
     * Converts a name to a kebab-case id (e.g. Fireball → fireball).
     */
    private function kebabize(string $name): string
    {
        return strtolower((string) preg_replace('/(?<!^)[A-Z]/', '-$0', $name));
    }

    /**
     * 值转 PHP 字符串内容（转义单引号，不含外层引号——模板已提供引号）。
     * Converts a value to PHP string contents (single quotes escaped, without the outer quotes — the template supplies them).
     */
    private function phpString(string $value): string
    {
        return str_replace("'", "\\'", $value);
    }

    /**
     * 值转 PHP 数字字面量（整数保留 .0 以维持 float 语义，纯整数输出整数字面量）。
     * Converts a value to a PHP numeric literal (integral floats keep a .0 suffix to preserve float semantics; pure ints render as int literals).
     */
    private function phpNumber(mixed $value): string
    {
        if (is_float($value)) {
            return (string) (sprintf('%.10F', $value) === sprintf('%.10F', floor($value))
                ? sprintf('%.1F', $value)
                : $value);
        }

        return (string) (int) $value;
    }
}
