<?php
// 由 make:event 生成 — 事件常量/载荷类骨架（EventDispatcher 派发用）。
// Generated by make:event — event constant/payload class skeleton (dispatched through EventDispatcher).
declare(strict_types=1);

namespace {ns};

/**
 * {class} 事件：NAME 常量供 EventDispatcher::dispatch 派发，载荷键约定见下方注释。
 * {class} event: the NAME constant feeds EventDispatcher::dispatch; payload key contract is documented below.
 */
final class {class}
{
    /** 事件名（如 player.killed / skill.cast）。Event name (e.g. player.killed / skill.cast). */
    public const NAME = '{event}';

    // 载荷键约定（payload key contract）——按需增删：
    // - 'entityId' => 目标实体标识 Target entity id.
    // - 'payload'  => 业务载荷 Business payload.
}
